### ISSUE TITLE
Issue with opening model file

### ISSUE THREAD

**Issue by alexander-alleman** [draeger-lab/ModelPolisher#102]
I don't know if something is wrong with my command setup or this is a java issue but I get:
 java.io.IOException: Could not open file at '/models/e_coli_core.xml' 

I have tried this with multiple sbml models.
I am using the ubuntu app on windows 10. 

Here is my command 

>docker-compose run -v /home/alex/ModelPolisher/models/e_coli_core.xml polisher java -jar /ModelPolisher-2.1-beta.jar --input=/models/e_coli_core.xml --output=/models/output/ee_coli_core_polished.xml --annotate-with-bigg=true --add-adb-annotations=true --output-combine=true 

I have the model.xml file in the ModelPolisher folder and a models folder 

Thanks for the help

-Alex

**Comment by mephenor** [comment]
Hi @alexander-alleman and sorry for the very late response, I did not get notifications for issues for quite some time and have not actively been working on this project since I started a new job.

The issues with your command seems to be `-v`:
This should rather look like `-v <path to folder containing models>:<path in container>` so in your case `-v /home/alex/ModelPolisher/models:/models`

**Comment by Schmoho** [comment]
To elaborate on this a little, the argument `-v <local directory>:<container directory>` accomplishes a [docker volume mapping](https://docs.docker.com/storage/volumes/) which is necessary for the container to manipulate files on your local system (from which it is isolated by default).

I hope you were able to resolve your issue, @alexander-alleman - could you maybe give a quick notice about it, so as to decide whether this issue can be closed?

**Comment by Schmoho** [comment]
I am closing this as it does not appear to be an issue anymore.
