### ISSUE TITLE
Known security vulnerabilities detected in third-party library

### ISSUE THREAD

**Issue by draeger** [draeger-lab/ModelPolisher#104]
Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10.8

**Comment by Schmoho** [comment]
As far as I can tell, we are currently using version 2.10.1 [see here](https://github.com/draeger-lab/ModelPolisher/blame/master/build.gradle#L56).

However, [our THIRD-PARTY.txt](https://github.com/draeger-lab/ModelPolisher/blob/master/THIRD-PARTY.txt#L6) is not quite up to date as far as I can tell.

Now it seems this was created by the [License Maven Plugin](https://www.mojohaus.org/license-maven-plugin/index.html)  at some point.

Since we are no longer using Maven, we could use a Gradle plugin instead, I have opened a PR to this effect.

**Comment by Schmoho** [comment]
I am renaming and retagging the issue to reflect what transpired to be the issue.
