### ISSUE TITLE
MetaNetX annotations not added properly

### ISSUE THREAD

**Issue by NantiaL** [draeger-lab/ModelPolisher#106]
When reading a model created with ModelPolisher with COBRApy, a series of warnings appear pointed to the fact that the MetaNetX annotations are not added in the desired form using identifiers.org. The following is an example of such a warning for the MetaNetX ID **MNXR98569**:

> MNXR98569 does not conform to 'http(s)://identifiers.org/collection/id' or'http(s)://identifiers.org/COLLECTION:id

Here is the annotation entry of the .XML file: 

```
<bqbiol:is>
    <rdf:Bag>
          <rdf:li rdf:resource="MNXR98569" />
          <rdf:li rdf:resource="https://identifiers.org/bigg.reaction/EX_glc__D_e" />
          <rdf:li rdf:resource="https://identifiers.org/biocyc/META:TRANS-RXN0-574" />
          <rdf:li rdf:resource="https://identifiers.org/metanetx.reaction/MNXR100188" />
          <rdf:li rdf:resource="https://identifiers.org/seed.reaction/rxn08617" />
          <rdf:li rdf:resource="https://identifiers.org/seed.reaction/rxn09679" />
          <rdf:li rdf:resource="https://identifiers.org/seed.reaction/rxn09875" />
   </rdf:Bag>
 </bqbiol:is>
```

**Comment by matthiaskoenig** [comment]
Yes, this is a bug. The correct prefixes are

https://registry.identifiers.org/registry/metanetx.chemical
`https://identifiers.org/metanetx.chemical`
https://registry.identifiers.org/registry/metanetx.reaction
`https://identifiers.org/metanetx.reaction`
https://registry.identifiers.org/registry/metanetx.compartment
`https://identifiers.org/metanetx.compartment`

**Comment by matthiaskoenig** [comment]
Thanks. So this is most likely my bug in the annotation database :/ Just opened an issue https://github.com/matthiaskoenig/annotatedb/issues/42
I wanted to make an update of the database in the next few days and can fix this as part of it.

**Comment by Schmoho** [comment]
@NantiaL I'll close this for now then

**Comment by matthiaskoenig** [comment]
Keep it open until it is fixed upstream, so other users can find it

**Comment by Schmoho** [comment]
I just realized this is also an issue with the data in BiGG anyways, so this issue is very much unresolved.

**Comment by matthiaskoenig** [comment]
I can normalize this in annotatedb, i.e. add the prefixes.

**Comment by GwennyGit** [comment]
**Update for the problem described in issue #103**
As I described before I got COBRApy warnings for my model created with CarveMe after ModelPolisher was used. These warnings were like stated above due to 165 MetaNetX identifiers being not properly added to the annotations. After taking a closer look at some of these identifiers I realised - as stated in issue #103 - that two MetaNetX identifiers were added by ModelPolisher. Today, I analysed the first 20 MetaNetX identifiers (see Table). So far I encountered four cases A to D. In each case the incorrectly added MetaNetX identifier could be removed.
Case A: Searching the improper added MetaNetX identifer in the MetaNetX database yielded an identifier that was already present and fits to the other specified databse identifiers.
Case B: Searching the improper added MetaNetX identifer in the MetaNetX database yielded the same identifier as is found with the properly added MetaNetX identifier.
Case C: Only the improper added MetaNetX identifier is present and searching this identifer in the MetaNetX database shows that it does not conform with any of the other specified database identifiers.
Case D: Searching the improper added MetaNetX identifer in the MetaNetX database yielded more than one result of which at least one yielded the same identifier as is found with the properly added MetaNetX identifier. This case contains two different scenarios so far. Either only the overlapping MetaNetX identifiers conform to the other specified database identifiers (D0) or all MetaNetX identifiers found with the improper added identifier conform to the other specified database identifiers (D1).
Case | MetaNetX ID | Notes | Status
:---: | :---: | :---: | :---:
A | MNXR98014 | Searching in MetaNetX yielded: MNXR124044, which is already present | Removed		
A | MNXR98016 | Searching in MetaNetX yielded: MNXR94809, which is already present | Removed	
A | MNXR98022 | Searching in MetaNetX yielded: MNXR94823, which is already present | Removed	
A | MNXR98037 | Searching in MetaNetX yielded: MNXR94861, which is already present | Removed
A | MNXR98054 | Searching in MetaNetX yielded: MNXR94968, which is already present | Removed
B | MNXR98057 | Searching in MetaNetX yielded: MNXR190466, <br>https://identifiers.org/metanetx.reaction/MNXR94983 also leads to: MNXR190466 | Removed &<br>Replaced ID in link with MNXR190466
A | MNXR97540 | Searching in MetaNetX yielded: MNXR95007, which is already present | Removed
C | MNXR98064 | Searching in MetaNetX yielded: MNXR137954, does not conform with specified BiGG ID! | Removed
A | MNXR98180 | Searching in MetaNetX yielded: MNXR95051, which is already present | Removed
A | MNXR98183 | Searching in MetaNetX yielded: MNXR101005, which is already present | Removed
A | MNXR98194 | Searching in MetaNetX yielded: MNXR142913, which is already present | Removed
D0 | MNXR98195 | Searching in MetaNetX yielded: MNXR152734 & MNXR152735,<br>https://identifiers.org/metanetx.reaction/MNXR95190 also leads to: MNXR152734,<br>Only MNXR152735 fits to specified BiGG & SEED IDs! | Removed &<br>Replaced ID in link with MNXR152735
A | MNXR98198 | Searching in MetaNetX yielded: MNXR95212, which is already present | Removed
D0 | MNXR98208 | Searching in MetaNetX yielded: MNXR192632 & MNXR192633,<br>https://identifiers.org/metanetx.reaction/MNXR95252 also leads to: MNXR192632,<br>Only MNXR192633 fits to specified BiGG & SEED IDs! | Removed &<br>Replaced ID in link with MNXR192633
B | MNXR98210 | Searching in MetaNetX yielded: MNXR190539,<br>https://identifiers.org/metanetx.reaction/MNXR95277 also leads to: MNXR190539 | Removed &<br>Replaced ID in link with MNXR190539
D1 | MNXR98220 | Searching in MetaNetX yielded: MNXR190115 & MNXR152783,<br>https://identifiers.org/metanetx.reaction/MNXR95292 also leads to: MNXR152783,<br>Both IDs fit to most of the other database IDs | Replace with https://identifiers.org/metanetx.reaction/MNXR190115 &<br>Replace ID in this link with MNXR152783 &<br>Put both identifiers close to each other
A | MNXR98226 | Searching in MetaNetX yielded: MNXR142915, which is already present | Removed
A | MNXR98228 | Searching in MetaNetX yielded: MNXR95496, which is already present | Removed
A | MNXR98247 | Searching in MetaNetX yielded: MNXR95663, which is already present | Removed
A | MNXR98248 | Searching in MetaNetX yielded: MNXR95682, which is already present | Removed
