### ISSUE TITLE
Update MIRIAM Registry to support new collections

### ISSUE THREAD

**Issue by mephenor** [draeger-lab/ModelPolisher#80]
Current identifiers.org registry file is outdated (version from 22 Jun 2018) and should be updated.

**Comment by draeger** [comment]
There should be a mechanism that updates this automatically upon building the project.

**Comment by matthiaskoenig** [comment]
Just some information, because I have been there with another project:
The old XML registry file is still working but will likely be deprecated in the near future (at least is the feedback I got when asking for changes in the dateformat). The latest registry content is now available via the api
https://docs.identifiers.org/articles/api.html
via the `getResolverDataset`

Resolver dataset

    Endpoint: https://registry.api.identifiers.org/resolutionApi/getResolverDataset
    Method: GET
    Description: Returns a copy of the whole registry.
    Example: https://registry.api.identifiers.org/resolutionApi/getResolverDataset

Not sure if you use the libmiriam/libregistry, but probably must be rewritten with the new JSON format.

Best M

**Comment by mephenor** [comment]
Custom parser for registry is implemented in refactoring branch now and should interact with all places in the code where annotations are handled correctly. Still need to add tests before merging into master

**Comment by Schmoho** [comment]
This appears to work fine. As the issue has been closed, I am moving it to finished.
